### ISSUE TITLE
Main branch named "master"

### ISSUE THREAD

**Issue by franz-josef-kaiser** [inuitless/inuit.css#1]
As [discussed on Twitter](https://twitter.com/pwcc/status/275712442464624640) the main branch should be named `master`.

Having a default branch of the name `master` (as in nearly every repo on this planet) allows to update all `git submodule`s with a single line from within your project (in bash/cmd).

```
git submodule foreach "(git checkout master; git pull)&"
```

Renaming a branch is actually pretty easy

```
# Example:
# git branch -m old_branch new_branch

git branch -m LESS master
```

**Comment by franz-josef-kaiser** [comment]
**Edit** Maybe you want to just add a new branch named `master` and link it to the `LESS` branch. I found an answer on SO that shows how [to make one branch an alias of another](http://stackoverflow.com/questions/549920/is-it-possible-to-alias-a-branch-in-git).

**Comment by peterwilsoncc** [comment]
It doesn't appear possible to push symbolic references to a remote server. To maintain this, I'd need to push both the LESS branch and the master branch on each update. I'm not keen to do this.

Hopefully I'm wrong, in which case are you able to send through the code reference?

p

**Comment by franz-josef-kaiser** [comment]
>  in which case are you able to send through the code reference?

sorry, but my English isn't good enough to understand this. Could try to write it in another way?

Thanks, 
K.

**Comment by peterwilsoncc** [comment]
I'm trying to find the command to do the pseudo code:

`push origin symbolic-ref:symbolic-ref`

If I set up a symbolic-ref locally, I need to push twice to update each branch.

Presently, you can achieve what you are after with:

`git submodule update`

You may also wish to try ( **untested** ):

```git submodule foreach "(git fetch origin; git merge FETCH_HEAD)&"

**Comment by franz-josef-kaiser** [comment]
Hey Peter,

I just gave it a brief test from within Bash and it _seemed_ to work (nothing to update on the current project). The only thing is that all my remote location would then have to be named `origin`, right? (Pretty tired already). Or am I confusing it with `git remote` now?

**Comment by peterwilsoncc** [comment]
I think you're right, yes.

**Comment by franz-josef-kaiser** [comment]
Question: When you go to "Settings" in the admin section of the repository, is your branch selected as "main" branch?
