### ISSUE TITLE
class .full-bleed in helper.less does not work

### ISSUE THREAD

**Issue by HeikoKampe** [inuitless/inuit.css#11]
Setting negative values with a minus in front of the unit function does not work for me:
margin-right:-unit(@base-spacing-unit, px)!important;

Moving the minus inside the function argument works as expected:
margin-right: unit(-@base-spacing-unit, px)!important;

Thank you very much for the less version of inuit.css

**Comment by nicoespeon** [comment]
Hi @HeikoKampe!

Thanks for reporting, I'll fix that and search for eventual similar typos in code :+1:
