### ISSUE TITLE
Create tag for v5.0-rc1

### ISSUE THREAD

**Issue by chrisvdp** [inuitless/inuit.css#12]
Can you guys create a tag for the math issues fixed for v5.0-rc1?

**Comment by nicoespeon** [comment]
Hi @chrisvdp!

Sorry for the delay of the answer (my god, few months later!).
As you can see, we didn't touch the project for a while. 

However, I'll try to find some time to catch up with latest tags of the SASS repo. I'll let you know, probably by the end of the month :smiley:

**Comment by nicoespeon** [comment]
I guess this is now completely outdated.

Please see https://github.com/inuitcss for the whole new inuit.css.
There should have been [a LESS version](https://github.com/inuitless) of it… but we definitely didn't have time to port it. If there is any volunteer, please let me know ;-)
